version: '3.8'

services:
  # Nginx
  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./packages/backend:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - backend
    networks:
      - app-network

  # PHP-FPM
  backend:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    volumes:
      - ./packages/backend:/var/www/html
    networks:
      - app-network
    depends_on:
      - db

  # MySQL
  mysql:
    image: mysql/mysql-server:8.0
    environment:
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    ports:
      - "3306:3306"
    volumes:
      - 'sail-mysql-data:/var/lib/mysql'
      - './docker/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
    networks:
      - app-network

  # Frontend
  frontend:
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./packages/frontend:/app
      - /app/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data: 