openapi: 3.0.0
info:
  title: セレクトショップマップ API
  version: 1.0.0
  description: セレクトショップマップのバックエンドAPI仕様

servers:
  - url: http://localhost
    description: ローカル開発環境

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    LoginCredentials:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          description: メールアドレス
        password:
          type: string
          format: password
          description: パスワード

    RegisterCredentials:
      type: object
      required:
        - name
        - email
        - password
        - password_confirmation
      properties:
        name:
          type: string
          description: ユーザー名
        email:
          type: string
          format: email
          description: メールアドレス
        password:
          type: string
          format: password
          description: パスワード
        password_confirmation:
          type: string
          format: password
          description: パスワード（確認用）

    AuthResponse:
      type: object
      properties:
        token:
          type: string
          description: 認証トークン
        user:
          type: object
          properties:
            id:
              type: integer
              description: ユーザーID
            name:
              type: string
              description: ユーザー名
            email:
              type: string
              description: メールアドレス
        expires_at:
          type: string
          format: date-time
          description: トークンの有効期限

    Error:
      type: object
      properties:
        message:
          type: string
          description: エラーメッセージ
        errors:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
          description: フィールドごとのエラーメッセージ

    Shop:
      type: object
      properties:
        id:
          type: integer
          description: 店舗ID
        name:
          type: string
          description: 店舗名
        address:
          type: string
          description: 住所
        latitude:
          type: number
          format: float
          description: 緯度
        longitude:
          type: number
          format: float
          description: 経度
        brands:
          type: array
          items:
            type: string
          description: 取扱ブランド一覧
        description:
          type: string
          description: 店舗説明
        average_rating:
          type: number
          format: float
          description: 平均評価
        created_at:
          type: string
          format: date-time
          description: 作成日時
        updated_at:
          type: string
          format: date-time
          description: 更新日時

    ShopInput:
      type: object
      required:
        - name
        - address
        - latitude
        - longitude
      properties:
        name:
          type: string
          description: 店舗名
        address:
          type: string
          description: 住所
        latitude:
          type: number
          format: float
          description: 緯度
        longitude:
          type: number
          format: float
          description: 経度
        brands:
          type: array
          items:
            type: string
          description: 取扱ブランド一覧
        description:
          type: string
          description: 店舗説明

    Review:
      type: object
      properties:
        id:
          type: integer
          description: レビューID
        shop_id:
          type: integer
          description: 店舗ID
        user_name:
          type: string
          description: ユーザー名
        rating:
          type: number
          description: 評価（1-5）
        comment:
          type: string
          description: コメント
        brands:
          type: array
          items:
            type: string
          description: 取扱ブランド一覧
        description:
          type: string
          description: 店舗説明
        created_at:
          type: string
          format: date-time
          description: 作成日時
        updated_at:
          type: string
          format: date-time
          description: 更新日時

paths:
  /auth/login:
    post:
      operationId: login
      summary: ユーザーログイン
      description: メールアドレスとパスワードでログインします
      tags:
        - 認証
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginCredentials'
      responses:
        '200':
          description: ログイン成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '401':
          description: 認証エラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '422':
          description: バリデーションエラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /auth/register:
    post:
      operationId: register
      summary: ユーザー登録
      description: 新しいユーザーアカウントを作成します
      tags:
        - 認証
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterCredentials'
      responses:
        '200':
          description: 登録成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '422':
          description: バリデーションエラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '409':
          description: メールアドレスが既に使用されています
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /auth/logout:
    post:
      operationId: logout
      summary: ログアウト
      description: 現在のユーザーをログアウトします
      tags:
        - 認証
      security:
        - BearerAuth: []
      responses:
        '200':
          description: ログアウト成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: ログアウトしました
        '401':
          description: 認証エラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /shops:
    get:
      operationId: getShops
      summary: 店舗一覧取得
      description: 全店舗の一覧を取得します
      tags:
        - 店舗
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Shop'

    post:
      operationId: addShops
      summary: 店舗追加
      description: 新しい店舗を追加します
      tags:
        - 店舗
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ShopInput'
      responses:
        '201':
          description: 作成成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Shop'
        '401':
          description: 認証エラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '422':
          description: バリデーションエラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
