openapi: 3.0.0
info:
  title: Select Shop Map API
  version: 1.0.0
  description: セレクトショップマップのAPI仕様書
servers:
  - url: 'http://localhost/api'
    description: ローカル開発環境
paths:
  /shops:
    get:
      summary: 店舗一覧の取得
      description: 登録されている全ての店舗情報を取得します
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Shop'
      operationId: get-shops
      tags:
        - Shop
    post:
      summary: 新規店舗の登録
      description: 新しい店舗情報を登録します
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ShopInput'
      responses:
        '200':
          description: 作成成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Shop'
        '400':
          description: バリデーションエラー
      operationId: add-shops
  '/shops/{id}':
    get:
      summary: 店舗詳細の取得
      description: 指定されたIDの店舗情報を取得します
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Shop'
        '404':
          description: 店舗が見つかりません
      operationId: get-shop
      tags:
        - Shop

components:
  schemas:
    Shop:
      type: object
      properties:
        id:
          type: integer
          description: 店舗ID
        name:
          type: string
          description: 店舗名
        address:
          type: string
          description: 住所
        latitude:
          type: number
          format: float
          description: 緯度
        longitude:
          type: number
          format: float
          description: 経度
        brands:
          type: array
          description: 取扱ブランド
          items:
            type: string
        description:
          type: string
          description: 店舗説明
      title: ''
    ShopInput:
      type: object
      required:
        - name
        - address
      properties:
        name:
          type: string
          description: 店舗名
        address:
          type: string
          description: 住所
        brands:
          type: array
          items:
            type: string
          description: 取扱ブランド
        description:
          type: string
          description: 店舗説明
