openapi: 3.0.0
info:
  title: セレクトショップマップ API
  version: 1.0.0
  description: セレクトショップの位置情報を管理するAPI

servers:
  - url: http://localhost:8000/api
    description: 開発サーバー

paths:
  /shops:
    get:
      summary: 店舗一覧の取得
      operationId: getShops
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Shop'
    post:
      summary: 新規店舗の追加
      operationId: createShop
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ShopInput'
      responses:
        '201':
          description: 作成成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Shop'

components:
  schemas:
    Shop:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        address:
          type: string
        latitude:
          type: number
          format: float
        longitude:
          type: number
          format: float
        brands:
          type: array
          items:
            type: string
        description:
          type: string
      required:
        - name
        - address
        - brands

    ShopInput:
      type: object
      properties:
        name:
          type: string
        address:
          type: string
        brands:
          type: array
          items:
            type: string
        description:
          type: string
      required:
        - name
        - address
        - brands 